apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-autoupdater
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - root.company.com
    # secretName: commodo-tls
  rules:
  - host: root.company.com
    http:
      paths:
      - path: /webhook
        pathType: Prefix
        backend:
          service:
            name: k8s-autoupdater-svc
            port:
              number: 3000
